### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by eeaston** [man-group/pytest-plugins#19]
We've had a number of pull requests from users on Windows, it would be great to get a CI slave made available for building and testing on Windows.

**Comment by jayvdb** [comment]
http://ci.appveyor.com/ is great for this.

**Comment by jcfr** [comment]
@eeaston  I suggest to setup Azure-Pipelines (it allows up to 10 parallel job while appveyor allows only one), if you are not familiar with this CI service, we could do a screen sharing and I could guide you through the process.

**Comment by eeaston** [comment]
Thanks @jcfr  - Azure is really taking off isn't it!  I've hooked up the auth plumbing and made a new org for manahl. Could you point me at any prior art for windows pipeline yaml files? I'll have a go at setting it up and get in contact if I get stuck.  If this works well we may as well move everything over to azure as there's no point having both circle and azure if azure supports windows and mac as well.

**Comment by jcfr** [comment]
I still think keeping CircleCI is relevant, it has a first class integration with docker.

Otherwise, here are few examples of azure-pipelines configuration:
* https://github.com/scikit-build/scikit-build/blob/master/azure-pipelines.yml 
* https://github.com/NeurodataWithoutBorders/nwb-docutils/blob/master/azure-pipelines.yml
* https://github.com/InsightSoftwareConsortium/ITK/tree/master/Testing/ContinuousIntegration
* https://github.com/conda-forge/scikit-build-feedstock/tree/master/.azure-pipelines

**Comment by eeaston** [comment]
Hi, we've got a working windows build on Travis now so I'll close this unless it is a blocker for any bugfixes / features.

**Comment by jayvdb** [comment]
https://travis-ci.org/github/man-group/pytest-plugins last ran 8 months ago.  I think it has been broken by the Travis CI switch to .com or some other change they have made recently.
